### ISSUE TITLE
How do you format a tag if it's not formatted yet with V2 APIs ? 

### ISSUE THREAD

**Issue by roshangm1** [revtel/react-native-nfc-manager#302]

**Comment by ReactTalent** [comment]
From v1, it was possible to format tag with requestWriteNdef([], {format=true}), but this function is disappeared from v2,
Where can I alternate this old function?
Main point is just to format and write new tag with these technologies : [ NfcA, MifaiClassic, NdefFormatable ]...
Please help me.
