### ISSUE TITLE
Writing doesn't work on IOS 14.1

### ISSUE THREAD

**Issue by traxx10** [revtel/react-native-nfc-manager#339]
Hello, i am currently writing and scanning on android but on ios, writing doesn't work.

`
let resp = await NfcManager.requestTechnology([NfcTech.Ndef],
        {
          alertMessage: 'Ready to Erase bracelet',
        },
      );
      Code never resolves or reaches here
      let bytes = Ndef.encodeMessage(formatTagNdefData);
      setIswriting(true);
      setLoading(true);
      setDetectedTag(true);
      await NfcManager.writeNdefMessage(bytes);
      await NfcManager.setAlertMessageIOS('I got your tag!');
`

How do i fix this?

**Comment by guoxianzhe** [comment]
same issues

**Comment by YusufBesim** [comment]
same issue

**Comment by avivku90** [comment]
same

**Comment by montecarlo0704** [comment]
same issue. anyone managed to solve this issue?

**Comment by YusufBesim** [comment]
> same issue. anyone managed to solve this issue?

No. Developer not replied yet

**Comment by traxx10** [comment]
Anyone resolved this yet?

**Comment by avivku90** [comment]
anyone resolved this ?

**Comment by fgrs** [comment]
same issue on ios 14.4.2

**Comment by fgrs** [comment]
@whitedogg13 do you have any solution to this?

**Comment by whitedogg13** [comment]
@fgrs write NDEF using iOS should work correctly, if you're using a formatted and writable NFC tag.

Please use latest v3, and try the following code snippet:
```javascript
import NfcManager, {
  NfcTech,
} from 'react-native-nfc-manager';

async function writeNdef({type, value}) {
    let result = false;

    try {
      await NfcManager.requestTechnology(NfcTech.Ndef, {
        alertMessage: 'Ready to write some NDEF',
      });

      let bytes = null;
      if (type === 'TEXT') {
        bytes = Ndef.encodeMessage([Ndef.textRecord(value)]);
      } else if (type === 'URI') {
        bytes = Ndef.encodeMessage([Ndef.uriRecord(value)]);
      }

      if (bytes) {
        await NfcManager.ndefHandler.writeNdefMessage(bytes);
        result = true;
      }
    } catch (ex) {
      console.warn(ex);
    } finally {
      NfcManager.cancelTechnologyRequest();
    }

    return result;
}
```

The above code snippet is extracted from [react-native-nfc-rewriter](https://github.com/revtel/react-native-nfc-rewriter).

This app has been published to [App Store](https://apps.apple.com/tw/app/nfc-rewriter/id1551243964), you can also try it and see if it can write to your target NFC tags.

Thanks!

**Comment by fgrs** [comment]
@whitedogg13 I forgot to reply, I solved the issue by adding into plist **com.apple.developer.nfc.readersession.iso7816.select-identifiers** and then values from this table [https://www.eftlab.com/knowledge-base/211-emv-aid-rid-pix/](url)

I recon this should be mentioned in the docs

**Comment by NathHorrigan** [comment]
@whitedogg13 The above fixed my issue, This should deffo be in the docs :)
