### ISSUE TITLE
ios 14.2 iphone 8 can't read tags

### ISSUE THREAD

**Issue by IrmantasVaracinskas** [revtel/react-native-nfc-manager#346]
Hello,

After user initialises scan and cancels it, SessionClosed event is usually not received (sometimes it is received, I would say it works fine about 30% of the time, maybe lower) for iOS 14.2 with iPhone 8 and so user cannot read another nfc tag, also SessionClosed event sometimes is not received after successfully scanning a tag. But it works fine on iOS 14.2 iPhone XR.

Tried on 2.2.0 library version and on 1.2.6.

Haven't tried on any other iPhone.

Maybe someone has similar issue?

Update: looks like this can also happen on iPhone XR but it is much more rare. From debugging it seems that if user calls registerTagEvent right after previous session closed then new session will be initiated but NFC scanner will not show up on screen and so user can't scan tag or cancel scanning but can't figure out if there's some delay I could put to scanning next tag, calling registerTagEvent after a second or two of when session was closed still sometimes reproduces this issue. Calling start (from what I can see it just sets session to nil) method or reopening the app solves the issue. But, from example code, calling start every time you wan't to scan a tag look like the right approach.

Thanks in advance

**Comment by IrmantasVaracinskas** [comment]
Update: looks like this can also happen on iPhone XR but it is much more rare. From debugging it seems that if user calls registerTagEvent right after previous session closed then new session will be initiated but NFC scanner will not show up on screen and so user can't scan tag or cancel scanning. You have to close and reopen app.

**Comment by sajadghawami** [comment]
i am experiencing that same issue!
