### ISSUE TITLE
writing bytes

### ISSUE THREAD

**Issue by fgrs** [revtel/react-native-nfc-manager#379]
how can I write plain bytes array using **writeNdefMessage** or different method? Basically I'd like to read and store the same data back onto the tag

**Comment by MaoJJJJJ** [comment]
I think the method that you looking for is transceive and sendMifareCommandIOS for IOS.

#293 
https://github.com/whitedogg13/react-native-nfc-manager/issues/293#issuecomment-815375326 

I've answered something similar here for writing password bytes onto the tag.
