### ISSUE TITLE
When can we expect Typescript support???

### ISSUE THREAD

**Issue by szabolcsveer** [revtel/react-native-nfc-manager#391]

**Comment by whitedogg13** [comment]
@szabolcsveer sorry for the late response.

I'd like to move to typescript as well! However, honestly speaking, it won't be too soon as a solo maintainer.

I will pin this issue to remind myself. BTW, if you're interested in helping this transition, please let me know :)

**Comment by hkar19** [comment]
i think this repo already has its type definition, or are we expecting some missing typing need to be addressed?

**Comment by frst-mg** [comment]
Does it not support apps with react native?
