### ISSUE TITLE
How to add or remove password to NTAG213 and NTAG216

### ISSUE THREAD

**Issue by SSinfo302** [revtel/react-native-nfc-manager#397]
How to add or remove password to NTAG213 and NTAG216 by react-native-nfc-manager

**Comment by whitedogg13** [comment]
It can be implemented by a sequence of `nfcAHandler.transceive()` commands.

You will need to read the datasheet from NXP first, but the whole idea looks like this:
- [setup] use standard T2T `write` (0xa2) command to configure the tag, including
  - set password, and password-ack
  - set read or write protection
  - set the starting block index to protect
- [access protected blocks] when you'd like to access the protected blocks, you will send an NXP proprietary command with your password. If correct, the tag will respond you with the password-ack. After this step, you will be able to access your tag's memory normally.

I have done this before, but I don't remember the detailed command and configuration block index, so you will need to consult the official datasheet from NXP.

Hope that helps.
