### ISSUE TITLE
a problem i met

### ISSUE THREAD

**Issue by feichi2016** [revtel/react-native-nfc-manager#402]
**when i click a button, the following callback function not run on first time**
**it's will run on next detection**
**what's causes this?**
**thanks**
```
NfcManager.requestTechnology(NfcTech.MifareClassic)
    .then(techName=> {
        console.warn(techName);
    });
...
```

**Comment by whitedogg13** [comment]
Hi, sorry but we haven't encountered this issue.

**Comment by feichi2016** [comment]
> 
> 
> Hi, sorry but we haven't encountered this issue.

oh,thanks any way.I'll take a look at it again
