### ISSUE TITLE
want to add pass protection for WRITE operation ....in ntag215/213

### ISSUE THREAD

**Issue by vinitchaudhari** [revtel/react-native-nfc-manager#411]
i want to protect write operation in ntag215/213.....
but didnt get it how to set pass protection ....
after setting password ...then how to authenticate ....then how to rewrite ntag 
i already referred documentation for ntag 213/215 but didnt get that hex code ...
anybody please help...

**Comment by OtayNacef** [comment]
check this

**Comment by OtayNacef** [comment]
> i want to protect write operation in ntag215/213..... but didnt get it how to set pass protection .... after setting password ...then how to authenticate ....then how to rewrite ntag i already referred documentation for ntag 213/215 but didnt get that hex code ... anybody please help...

Hey check this  example https://github.com/whitedogg13/nfc-pokemon-app/blob/main/src/NfcUtils/ensurePasswordProtection.js

**Comment by vinitchaudhari** [comment]
can you please explain little bit more about how to set password using
string ?e.g i want to set password "hello world"
thanks in advance
