### ISSUE TITLE
[Question] P2P, peer to peer, phone to phone data transfer

### ISSUE THREAD

**Issue by jellyfish-tom** [revtel/react-native-nfc-manager#428]
Hello, 

Is phone to phone data transfer possible? Ideally iOS <-> Android, not only within one system.
I've seen this question asked 3 years ago and answer was that bidirectional API is not open. Has anything changed since then? 

Best regards, 
Tom

**Comment by thanveershah** [comment]
> @jellyfish-tom Hi, it's still not possible even today.

Really? both android and ios ?
