### ISSUE TITLE
ISO15693 Detection

### ISSUE THREAD

**Issue by msoose** [revtel/react-native-nfc-manager#432]
Is it necessary to declare anything before attempting to read an ISO15693 tag to indicate the chip to expect an ISO15693 tag on iOS? I haven't needed to 'set' a specific technology on Android and my tag is detected and read just fine, but it doesn't detect it on an iOS device.

I'm using NfcManager.setEventListener(NfcEvents.DiscoverTag, (tag) => {

Thanks in advance

**Comment by msoose** [comment]
Looks like I should be using NfcManager.requestTechnology() for this for iOS

I still can't seem to get a UID though...

let iostech = NfcTech.Iso15693IOS;
let iosnfc = NfcManager.requestTechnology(iostech, {alertMessage: 'Tap to scan'})
      console.log('[+] iOS:' + iosnfc)
      let tag = NfcManager.getTag();
      console.log('[+] UID:' + tag.id);

Returns undefined for tag.

**Comment by msoose** [comment]
Returning tag stringify I get _U:0, _V,0, _W:null and X:null.

**Comment by gregogalante** [comment]
@msoose I'm getting the same problem. How do you solve this?

**Comment by msoose** [comment]
I used requestTechnology() on iOS and stuck with setEventListener() for Android devices.

**Comment by msoose** [comment]
> @msoose I'm getting the same problem. How do you solve this?

 I used requestTechnology() on iOS and stuck with setEventListener() for Android devices.

**Comment by Sixzero** [comment]
So the iOS is working with requestechnology being set?
For android I requetested technology: 
NfcManager.requestTechnology(NfcTech.NfcV)
