### ISSUE TITLE
[Android] NfcManager.setEventListener not work

### ISSUE THREAD

**Issue by godlatro** [revtel/react-native-nfc-manager#436]
I need read tags everytime without manually push button like NfcProxy.readTag()
This code Has no effect:

          NfcManager.setEventListener(
            NfcEvents.DiscoverBackgroundTag,
           ()=>alert('Event Listener'),
          );

          NfcManager.setEventListener(
            NfcEvents.DiscoverTag,
            ()=>alert('Event Listener'),
          );

This work first time after launch
await NfcManager.getBackgroundTag();

**Comment by SeanRog** [comment]
It doesn't work for me either. It looks like there's no corresponding @ReactMethod in NfcManager.java.
