### ISSUE TITLE
Delay with cancelTechnologyRequest

### ISSUE THREAD

**Issue by garridio85** [revtel/react-native-nfc-manager#448]
Hi,

I am having an issue with the clean-up function. it works but it has a bit of a delay. is there any way the NFC popover can close as soon as the NFC is scanned?

I am using the following:

```
const cleanUp = () => {
        NfcManager.cancelTechnologyRequest().catch(() => 0);
};
```

**Comment by garridio85** [comment]
Sorry my mistake I needed to use the listener :-p

**Comment by whitedogg13** [comment]
Hi @garridio85 , your code looks correct, but the delay is from iOS natively so we cannot control it.
