### ISSUE TITLE
How to read a big NFC message separated on few packets 

### ISSUE THREAD

**Issue by ruziev-dev** [revtel/react-native-nfc-manager#457]
I have to get some information from anoher device by NFC.
When I read it with using "NFC tool" application, I am getting long message (see screenshot), but when I try to connect with using react-native-nfc-manager I get small part of this message. 

 ```
LOG    "auth": {
                        "WORK*": 1,
                        "PINC*": 65535,
                        "USED": 1,
                        "GOOD": 0,
                        "SNUM*": 102,
                        "FNUM*":
```
Are there some settings in NfcManager which can help me to get full NFC info?🥺

![Screenshot_20211122-144613](https://user-images.githubusercontent.com/74172766/142857805-6673276f-dc2d-4ac5-b334-f8cdce335065.png)

**Comment by Langsdorf** [comment]
The message is generated by you? Maybe you can pack the message using [msgpack](https://www.npmjs.com/package/msgpack) then unpack when you read the NFC tag. 

I don't know if it is possible but worths a try.
