### ISSUE TITLE
How to open my app

### ISSUE THREAD

**Issue by freeridre** [revtel/react-native-nfc-manager#460]
Hi there!
So, when my app is closed, and I read a specific NDEF message from the tag, I would like to open my app by NDEF message of the tag, even if my app is in background.
How could I implement this?

**Comment by Langsdorf** [comment]
Try using [deep linking](https://blog.logrocket.com/understanding-deep-linking-in-react-native/)

**Comment by freeridre** [comment]
> Try using [deep linking](https://blog.logrocket.com/understanding-deep-linking-in-react-native/)

When my app is not running? Should I have to implement a service? what about Headless JS? And I use expo managed workflow.

**Comment by Langsdorf** [comment]
In the post I mentioned, it says you can use even if  your app is closed (the link will open it up)

![image](https://user-images.githubusercontent.com/13462281/144599516-c52f32e1-a1c0-4f77-9281-038c00960d01.png)

**Comment by likrot** [comment]
> > Try using [deep linking](https://blog.logrocket.com/understanding-deep-linking-in-react-native/)
> 
> When my app is not running? Should I have to implement a service? what about Headless JS? And I use expo managed workflow.

@freeridre You can write such information on NFC chip (with [this](https://play.google.com/store/apps/details?id=com.wakdev.wdnfc&hl=en_US&gl=US) app for instance). 
When scanning with NFC, your app will be open (if it's been installed).

I'm not sure about expo but it works with bare RN app or with an app written with Kotlin so I think this is a system thing.
