### ISSUE TITLE
Cannot use library in Jest tests

### ISSUE THREAD

**Issue by shanedaugherty** [revtel/react-native-nfc-manager#461]
When I try to use this library in a Jest environment it fails with the following error: 
```
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.
```

Note: I'm not trying to test the native modules, I would simply like to have some unit tests that access the `Ndef` export via ```import {Ndef} from 'react-native-nfc-manager```.

Repository with an example (`git clone`, `npm install`, `npm run test` to reproduce): 
https://github.com/shanedaugherty/react-native-nfc-manager-jest-test

**Comment by skiqh** [comment]
For anybody having the same problem: Try adding this to your `jestSetupFile.js` (see https://jestjs.io/docs/configuration#setupfiles-array)

```javascript
jest.mock("react-native-nfc-manager", () =>
	require("react-native-nfc-manager/src/__mocks__/NativeNfcManager.js")
)
```
