### ISSUE TITLE
new NativeEventEmitter() was called with a non-null argument without the required removeListeners method.

### ISSUE THREAD

**Issue by likrot** [revtel/react-native-nfc-manager#472]
Hi.

First, thanks for the lib. It is very useful.

After I upgraded RN to version 0.66.4 I have such warning in terminal:

`'new NativeEventEmitter()' was called with a non-null argument without the required 'removeListeners' method.`

Some other libraries have already fixed this. [Here are some more details](https://github.com/react-native-netinfo/react-native-netinfo/issues/486)

I've created PR based on that solution https://github.com/revtel/react-native-nfc-manager/pull/471

**Comment by whitedogg13** [comment]
#471 merged, thanks!
