### ISSUE TITLE
TagEvent id is string instead of number[]

### ISSUE THREAD

**Issue by raydenvoldeskine** [revtel/react-native-nfc-manager#476]
react-native-nfc-manager: 3.1.0

Running on Android (do not know if the problem exist on iOS yet).
Reading tag in TypeScript using NfcManager.getTag() 

EXPECTED:  As the TagEvent id is defined like this in index.d.ts 

```
  export interface TagEvent {
    ndefMessage: NdefRecord[];
    maxSize?: number;
    type?: string;
    techTypes?: string[];
    id?: number[];
  }
```
I expect it to be a number array.

OBSERVED: 

However if I dump the attribute tyoe with typeof it is "string"

**Comment by whitedogg13** [comment]
Hi @raydenvoldeskine your observation is correct! The typing is wrong, I will fix it soon.

**Comment by whitedogg13** [comment]
Fixed in `v3.11.3`

**Comment by raydenvoldeskine** [comment]
Is the change sufficient ? I mean the issue happens "between the worlds"  - conversion from native to type script, would simple change of type script type solve it?

**Comment by whitedogg13** [comment]
@raydenvoldeskine yes, it’s just a typing issue and native side will always set the `.id` field to string if it presents.
