### ISSUE TITLE
How i change de KEY auth for sector ?

### ISSUE THREAD

**Issue by juanmoura** [revtel/react-native-nfc-manager#477]
Can i update a key for auth in the sector ?
I tried fell ways, but i can't do it.

**Comment by javix64** [comment]
first of all, in the sector, between the keyA and keyB:
![image](https://user-images.githubusercontent.com/58471170/154159323-b04f0b43-81a1-4b01-bc20-8891cabee4cd.png)
there are 4 bytes: 40 F7 8B 00, this part of the sector tells you if the sector, specially the block of keys is writable. after that you can edit it.
Almost in android-java is working like that, idk in react-native, you can try it :smile:
