### ISSUE TITLE
Android demo app is country-restricted

### ISSUE THREAD

**Issue by Arachnid** [revtel/react-native-nfc-manager#485]
I live in New Zealand, and the Google play store claims the app is not available in my country.

**Comment by whitedogg13** [comment]
@Arachnid thanks for reporting! We will check it out to see if we put any limitations there. 

In the meantime, please feel free to grab the APK [here](https://github.com/revtel/react-native-nfc-rewriter/releases).

Thanks!

**Comment by ulayab** [comment]
Hi @Arachnid, we have enabled the [NFC ReWriter](https://play.google.com/store/apps/details?id=com.washow.nfcopenrewriter) availability of  New Zealand in Google play store.

Please let me know if there are any problems!

**Comment by Arachnid** [comment]
Thank you!
