### ISSUE TITLE
Need advices for a special NFC payment setup

### ISSUE THREAD

**Issue by changtimwu** [revtel/react-native-nfc-manager#493]
Hi! 
Well, this is a question rather than an issue.  I just couldn't found a forum having more mobile payment experts than this repo.  Feel free to close it if you think it's totally irrelevant.

Here is the question.  [Somebody proposed using NFC for crypto payment](https://github.com/solana-labs/solana-pay/issues/57). 

Base on my understanding, typically, a standard NFC payment works in this way.
```
 Merchant (NFC reader) <-----  User( NFC tag)
```

In [this guy's idea](https://github.com/solana-labs/solana-pay/issues/57#issuecomment-1030354739), it's like
```
Merchant ( programmable NFC tag) ----->  User( NFC reader)
```

While I haven't seen NFC payment done in such a way,  it really can avoid a long lasting problem  --  [iOS doesn't open tag emulation function to 3rd apps](https://learn.gototags.com/articles/iphone-13-using-nfc-and-nfc-tags-with-ios-15-in-2021#:~:text=There%20is%20one%20remaining%20limitation%20that%20Core%20NFC%20can%20not%20be%20used%20for%20payment%20related%20apps%20as%20this%20would%20be%20a%20competitor%20to%20Apple%20Pay.%20There%20are%20several%20campaigns%20and%20lawsuits%20relating%20to%20this.).  

How do you guys think about this?

**Comment by sailplaneTW** [comment]
Hello
Sry for my late reply.

I am co-founder of RevtelTech, the major maintainer of this repo.
Actually we have some idea and developing for this scenario.

Maybe we could do more discussion around this topic :)

This is my email : sam.huang@revteltech.com
I look forward to hearing from you soon  :)
