### ISSUE TITLE
Disable apple pay

### ISSUE THREAD

**Issue by freeridre** [revtel/react-native-nfc-manager#494]
Hello devs,
Are there any way to disable apple pay, while I use my ndef app? Because if my Iphone is close to the nfc reader my apple pay gui opens, and I do not want that...

**Comment by mohmmadmoussa1988** [comment]
Any update, is there any solution for the stated problem?

**Comment by bmweapplinse** [comment]
@freeridre Did you find any work around for this?

**Comment by mohmmadmoussa1988** [comment]
@bmweapplinse yes,
you should send an email to 
apple-pay-inquiries@apple.com
apple-pay-provisioning@apple.com

having that info at the header

Company: xxxx
Team ID: xxx
Apple ID: xxxx
Application ID: xxxx

then explain your need, I did this and they provided me with needed entitlement

**Comment by bmweapplinse** [comment]
> @bmweapplinse yes, you should send an email to [apple-pay-inquiries@apple.com](mailto:apple-pay-inquiries@apple.com) [apple-pay-provisioning@apple.com](mailto:apple-pay-provisioning@apple.com)
> 
> having that info at the header
> 
> Company: xxxx Team ID: xxx Apple ID: xxxx Application ID: xxxx
> 
> then explain your need, I did this and they provided me with needed entitlement

And then how to use that entitlement from the app side in react native?

**Comment by mohmmadmoussa1988** [comment]
@bmweapplinse  still didnt find a way to do make it with reactnative, any update from your side?

**Comment by BhavyaKoshiya** [comment]
@mohmmadmoussa1988 @freeridre Did you manage to add this in the app?
