### ISSUE TITLE
TypeError: null is not an object (evaluating 'NativeNf Manager[name]')

### ISSUE THREAD

**Issue by martin12345678900** [revtel/react-native-nfc-manager#501]
Hello, i have the following problem. When i open my react-native expo app from Expo Go using my android device on NfcManager.start() im getting the following error: TypeError: null is not an object (evaluating 'NativeNf Manager[name]'). Please someone help me to solve this issue <3

**Comment by ahirwar-ankit** [comment]
+1
I'm Also facing the same problem. Cannot start `NfcManager()`.

**Comment by whitedogg13** [comment]
Hi @martin12345678900 & @ahirwar-ankit while using `Expo Go`, you **CANNOT** add `custom native modules` like this one. 

You should consider to use `Expo EAS` if NFC is required for you app, and the related doc is [here](https://github.com/revtel/react-native-nfc-manager#expo)
