### ISSUE TITLE
Jest testing: "Invariant Violation: Native module cannot be null."

### ISSUE THREAD

**Issue by lindan4** [revtel/react-native-nfc-manager#509]
I am looking to integrate a bare Expo application with Jest for testing. I am working on with Jest but am running into the following issue.

```
FAIL   iOS  __tests__/App.test.js
  ● Test suite failed to run

    Invariant Violation: Native module cannot be null.

      46 | import _ from "lodash";
      47 | import { manipulateAsync, SaveFormat } from "expo-image-manipulator";
    > 48 | import NfcManager, { NfcEvents, Ndef } from "react-native-nfc-manager";
         | ^
```
Someone else had also opened an issue but it was closed due to inactivity. I have shallow rendered the application but still have this issue. Is there any way to fix this or will it soon be addressed.

**Comment by joekabogo** [comment]
Experiencing the same issue too. Did you manage to work around it @lindan4 ?
