### ISSUE TITLE
Can i scan tag without button click event?

### ISSUE THREAD

**Issue by kojoo112** [revtel/react-native-nfc-manager#510]
I want to scan tag without button click event.

how can i do it?

please tell me

Phone: Galaxy S10 5G

**Comment by ShiriNmi1520** [comment]
[Example code](https://github.com/revtel/react-native-nfc-manager#usage) provided in readme should do the trick 🤔

**Comment by Helicosaurus-Rex** [comment]
@ShiriNmi1520 The exemple you linked to uses an onPress event.

I also don't get how you are supposed to read tags without attaching the processing logic onto another UI event. Do I need to use NFCManager.ndefHandler and the likes? I find the exemples a bit vague.

**Comment by ShiriNmi1520** [comment]
@Helicosaurus-Rex Just found a PR mention about updating example code that didn't merge #470, I'll dig into it

**Comment by Helicosaurus-Rex** [comment]
Thanks! I'll dig into it as well.

**Comment by ShiriNmi1520** [comment]
@kojoo112 @Helicosaurus-Rex 
I've created an [example project](https://github.com/ShiriNmi1520/nfc_test/blob/e5aef49082620fecf515309955b09cbb16ddd086/App.js) using expo bare workflow and some code from #470 that reads NFC tag without clicking anything, sees if this helps or need any improvement

**Comment by Helicosaurus-Rex** [comment]
Huge thanks! I should be able to make it work from here.

**Comment by kojoo112** [comment]
@ShiriNmi1520 THANK YOU SOOOOOOOOO MUCH!!!!

**Comment by ShiriNmi1520** [comment]
No problem, let me know if there's another problem and I'll try to figure it out :)

**Comment by yfs-2000** [comment]
@ShiriNmi1520  If the setEventListener method is used and nfcVHandler's transceive method is used, a "No tech request available" warning will appear

**Comment by ShiriNmi1520** [comment]
> @ShiriNmi1520 If the setEventListener method is used and nfcVHandler's transceive method is used, a "No tech request available" warning will appear

I'll look into it

**Comment by flyskywhy** [comment]
System NFC alert modal can't show on my Android phone, so be this wrapper [react-native-nfc-rw](https://github.com/flyskywhy/react-native-nfc-rw?tab=readme-ov-file) to read and write NfcV on iOS and Android , maybe you can ref to it.

And for keep reading tags, Android can do it by change the position of `destroyNfc()`, just modify the `showNfcModal()` and `dismissNfcModal()` in `README.md` of `react-native-nfc-rw` into
```
  // will be invoked on iOS and Android by a button in render()
  showNfcModal = () => {
    initNfc({
      alertEnableNfc: this.alertEnableNfc,
      alertNoNfcSupport: this.alertNoNfcSupport,
      alertNfcOther: this.alertNfcOther,
      onDiscoverTag: this.onDiscoverTag,
      alertIosMessage: 'Let your phone tap the device to add',
      alertAndroidOpen: () => this.setState({modalNfc: true}),
      alertAndroidClose: () => {}, // modify to THIS
    });
  };

  // will only be invoked on Android
  dismissNfcModal = () => {
    destroyNfc(); // modify to THIS
    this.setState({
      modalNfc: false,
    });
  };
```
