### ISSUE TITLE
Wireless Charging and 2way data transfer.

### ISSUE THREAD

**Issue by iprimo** [revtel/react-native-nfc-manager#512]
Hi,
I am working on a Smartphone accessory and struggling with enabling Wireless Charging and 2Way NFC comms.

Simple work flow of the device is:
1. On the Smartphone App (initiator) , user click on NFC wireless charing,
2. When charge starts the Target hardware starts to charge + its MicroController (MCU) starts P2P comms with Smartphone via NFC,
3. The Target device's MCU, sends analytics of the device to Smartphone (initiator)
4. Initiator processes the data and sends new baseline data to Target MCU, and instructs the old analytic data to be wiped for privacy reasons and turn a LED On to illustrate completion of the process.
5. Device continues charging until charge is complete to device removed from the NFC pad.

I appreciate if you could help me with this. I started to doubt if Wireless charging and Send\Receive data at the same time is possible on react-native-nfc-manager (or in general on Android\IOS)

Thanks

**Comment by ShiriNmi1520** [comment]
@iprimo 
Looks like you're trying to charge other devices with a smartphone (iOS or Android), it's called ```reverse charging``` if I understand correctly.
Currently, react-native-nfc-manager works with reading/writing NFC tags, I think the reverse charging feature should be done/supported at the device OS level.
