### ISSUE TITLE
Error from requestTechnology() 

### ISSUE THREAD

**Issue by FladioArmandika** [revtel/react-native-nfc-manager#513]
```
 try {
      await NfcManager.requestTechnology(NfcTech.Ndef);
      const tag = await NfcManager.getTag();
      console.warn('Tag found', tag);
    } catch (ex) {
      console.warn('Oops!', ex);
    } finally {
      NfcManager.cancelTechnologyRequest();
    }

```

I tried await `NFCManager.requestTechnology(NfcTech.Ndef);` function but it just catches an error like this
`Exception: decodeObjectForKey: class "NFFieldNotificationECP1_0" not loaded or does not exist`
  
  and `didInvalidateWithError`
  
 Platform : iOS (Both)

**Comment by ShiriNmi1520** [comment]
If possible can you provide full code about you trying to implement reading NFC?
 I'll need your environment info (package.json or ```react-native info```) to see if I can help you with that
