### ISSUE TITLE
How to write using nfcV 

### ISSUE THREAD

**Issue by Daba314** [revtel/react-native-nfc-manager#526]
I've checked the example with nfcA in the Pokemon app, but I can not implement the same logic for  NfcV. What's the first parameter which I should put here?
await NfcManager.nfcVHandler.transceive([????, 4, ...blockData]);

**Comment by whitedogg13** [comment]
Hi @Daba314 , thought we also support `transceive` for `NfcV`, however different tags have different commands so you generally cannot expect to achieve the same functionality by sending the same payload to different tags.
