### ISSUE TITLE
Read the same tag sometime will have diffirent information.

### ISSUE THREAD

**Issue by yanwzhang** [revtel/react-native-nfc-manager#539]
react-native: 0.64.1
android: 12

When I read one tag, sometime will occur diffrent read result. like this:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/64258970/177281387-ad1f8fd0-4045-4ec5-b12d-817818e96941.png">
<img width="642" alt="image" src="https://user-images.githubusercontent.com/64258970/177281444-88bf7b4f-3445-4caa-8d0e-92855f4dcbb8.png">

it is the same id, but sometimes it will miss ndefMessage.

**Comment by yanwzhang** [comment]
react-native-nfc-manager: 3.11.0

**Comment by yanwzhang** [comment]
when I use NFC reWriter to scan the same NFC tags. 
it's the diffrent result:
<img width="213" alt="image" src="https://user-images.githubusercontent.com/64258970/177549176-046708a1-de04-4c30-a611-10a6065d12e4.png">
the top screen doesn't have nefMessage and other info. but when I scan again, it will have:
<img width="234" alt="image" src="https://user-images.githubusercontent.com/64258970/177549739-7ed471de-8333-4050-87eb-f17ee7b4eeea.png">

**Comment by yanwzhang** [comment]
> Have the same issue on iOS in our prod app. I'm not able to reproduce it myself but I can see it in our Firebase Crashlytics logs, `ndefMessage` is sometimes not present.
> 
> ![Capture d’écran, le 2022-07-11 à 13 31 40](https://user-images.githubusercontent.com/18152986/178323417-43d2b994-d85b-4f83-8c0b-345466785053.png)
> 
> `react`: 0.64.1 `react-native-nfc-manager`: 3.13.2
> 
> EDIT: I am able to consistently reproduce the issue. I initiate the NFC read when I'm already at certain distance of the tag. see the video below:
> 
>  PXL_20220712_145253641.mp4 
> @yanwzhang My solution to fix it for now was to implement the old style use with event listening as shown on the module's page, hope it helps!

it seems to work to implement the old style use with event listening, I'll try more times to test this way, thank you.

**Comment by yanwzhang** [comment]
> Have the same issue on iOS in our prod app. I'm not able to reproduce it myself but I can see it in our Firebase Crashlytics logs, `ndefMessage` is sometimes not present.
> 
> ![Capture d’écran, le 2022-07-11 à 13 31 40](https://user-images.githubusercontent.com/18152986/178323417-43d2b994-d85b-4f83-8c0b-345466785053.png)
> 
> `react`: 0.64.1 `react-native-nfc-manager`: 3.13.2
> 
> EDIT: I am able to consistently reproduce the issue. I initiate the NFC read when I'm already at certain distance of the tag. see the video below:
> 
>  PXL_20220712_145253641.mp4 
> @yanwzhang My solution to fix it for now was to implement the old style use with event listening as shown on the module's page, hope it helps!

I test many times, it will some time occur the same situation, ndefMessage sometimes doesn't have.

**Comment by gigeos** [comment]
Still occur for me. I tried to read tag with other app like NFC Tools and I reproduce the same situation.
According to my analytics, this happens on both ios 15 and 16

Type: NXP NTAG215
Data format: NFC Type 2
