### ISSUE TITLE
Imitating rfid cards

### ISSUE THREAD

**Issue by mrados7** [revtel/react-native-nfc-manager#542]
Hello guys! 
Is it possible with this lib to imitate rfid cards. e.g. rfid cards have uid that is read to enter parking lot or whatever.  Could phone emit same signal to imitate rfid card? If so is it supported by both Android & iOS?

Thanks in advance.

**Comment by whitedogg13** [comment]
Hi @mrados7 the feature you're looking for is generally called NFC card emulation, which is only available on Android (called HCE, or Host-based Card Emulation). Our library currently doesn't support it.
