### ISSUE TITLE
How can I open my application and get tag information when app is in kill state or in background?

### ISSUE THREAD

**Issue by krushalikevadiya** [revtel/react-native-nfc-manager#543]
I need to open my iOS app when user scan NFC tag.Also i need tag id which is scanned by user.
Library verison : "react-native-nfc-manager": "3.9.0"
React native version :  "react-native": "0.64.2",

**Comment by whitedogg13** [comment]
It's totally possible, and in my opinion the simplest way to achieve that is to use custom scheme & deep link with NDEF RTD_URI.
- Define your custom scheme, and support deep linking for your app using this scheme.
- Write your deep link with custom scheme into NFC tag with RTD_URI, which are supported by both Android / iOS

**Comment by krushalikevadiya** [comment]
Thanks for your reply I'll try this.

**Comment by gigeos** [comment]
Yes indeed it's the good way and it works well. But how to read tag data?
