### ISSUE TITLE
iOS cancelTechnologyRequest -> requestTechnology -> Duplicate registration

### ISSUE THREAD

**Issue by asagalovskiyLB** [revtel/react-native-nfc-manager#546]
In iOS, `NfcManager.cancelTechnologyRequest()` does not immediately cancel the request, and has no feedback event about when the request has been canceled. If you execute  `NfcManager.requestTechnology()` in the meantime, it will return with an error: `Oops! [Error: Duplicated registration]`

How to reproduce:
1. Activate the scan with `NfcManager.requestTechnology()`
2. Scan the tag
3. Immediately swipe down on the iOS's scan prompt screen to hide it.
4. Activate the scan again with `NfcManager.requestTechnology()`

**Comment by whhotw** [comment]
+1

**Comment by chrisfinch** [comment]
+1

**Comment by wordisthebird** [comment]
Any update on this? or how to handle error?

**Comment by erikostling** [comment]
:+1

**Comment by erikostling** [comment]
The only solution that I've found to this so far is delaying the read requestTechnology call (2 seconds). Seems not like an ideal solution.

**Comment by dcanora** [comment]
Has anyone found a solution to this? I believe it may help me solve my issue... I experienced this duplicate registration problem, so I tried to call requestTechnology() once, then loop through calling getTag() multiple times, and finally cancelTechnology() when the user is done but I'm getting the issue outline in #645.
