### ISSUE TITLE
Using NFC after using the barcodescanner

### ISSUE THREAD

**Issue by Bludecoder2** [revtel/react-native-nfc-manager#549]
I am using the barcodescanner in my app to simply scan codes and put the content within an textinput.
Works perfectly.
I’m enabeling the camera by setting a a state (isCamera) true or false. If true show <Barcodescanner … /> if false do nothing.

Now I also want to be able to use NFC tags in my app. It also works perfectly on its own without.

No my Problem is if I use the barcodescanner to fill one textinput then nfc stops working for the entire app. Nomater if I navigate to a different Screen or not.

I also postet an example of my code on [stackoverflow]((https://stackoverflow.com/questions/73391226/react-native-nfc-manager-stops-working-after-i-use-expo-barcode-scanner)

I now that this is, as of right now, an andoird 12 only problem. Since nfc is disabled while the camera is active.

Can anyone help me with this?

**Comment by orhangazi** [comment]
Yes, I had the same issue. How can I use both camera and NFC at the same time?
