### ISSUE TITLE
 Unsupported Tag Api with android device

### ISSUE THREAD

**Issue by Chenbao2021** [revtel/react-native-nfc-manager#553]
Hello,
  I am trying to use this package between two android device , and when i am trying to write  a tag from one to another  i received this information 'unsupported tag api error ' . Is there anyone meets same error?

**Comment by whitedogg13** [comment]
Currently this library is targeting a device (as a NFC reader) vs a NFC tag or card, not a device to another device (called NFC P2P), thanks!

**Comment by Henry-E** [comment]
The fact that this library doesn't support this use case needs to be documented more clearly. Device to device using regular NFC communication is quite a popular use case.
