### ISSUE TITLE
“Please tap NFC tags” text Localization language

### ISSUE THREAD

**Issue by wowtrxqn** [revtel/react-native-nfc-manager#558]
<img width="427" alt="WechatIMG608" src="https://user-images.githubusercontent.com/24369118/190311259-64f4f5dd-df80-44bf-a7cb-c455d09f183c.png">

**Comment by wowtrxqn** [comment]
the “Please tap NFC tags” is not simple chinese

**Comment by NiccoloCase** [comment]
have you found a solution?

**Comment by CallbackDan** [comment]
+1

**Comment by gskachkov** [comment]
Just use property `alertMessage`, or `nfcManager.setAlertMessage`
