### ISSUE TITLE
Support for iOS ProximityReader

### ISSUE THREAD

**Issue by tylercallison** [revtel/react-native-nfc-manager#559]
With iOS 16, Apple released the [ProximityReader API](https://developer.apple.com/documentation/ProximityReader). This could be used for a variety of uses such as iPhone to iPhone NFC data transfer. 

Under the secure layer of Apple Pay, this could be a major feature to enable developers to create secure data transfers using NFC.

More info:
https://developer.apple.com/tap-to-pay/
https://developer.apple.com/documentation/ProximityReader

**Comment by whitedogg13** [comment]
@tylercallison thanks for the infomation! I'll definitely take a look!

**Comment by tylercallison** [comment]
@whitedogg13 Do you think this would be something we might see implemented within this library?
