### ISSUE TITLE
Is there a way after a successful NFC tag read to hide or disable the native UI modal for iOS?

### ISSUE THREAD

**Issue by ceyanesb** [revtel/react-native-nfc-manager#567]
I am developing an app where once the user scans a TAG the app should redirect the user to another screen but the prebuilt UI is kept shown for a long time, so how can I disable or hide that NFC UI after i know that the reading has been successful? @poison @whitedogg13

**Comment by snjxf** [comment]
Please tell me why my ios doesn't respond after the scan box pops up, thank you
