### ISSUE TITLE
Mifare Classic is not working

### ISSUE THREAD

**Issue by gshoanganh** [revtel/react-native-nfc-manager#572]
i tried your example, it doesn't seem to work.
your ex: [AndroidMifareClassic.js](https://github.com/poison/react-native-nfc-manager/blob/feature/mifareclassic-write/example/AndroidMifareClassic.js)
at line 263, it actually stopped. (follow the arrow.)

```
this.setState({ isDetecting: true });
    NfcManager.registerTagEvent(tag => console.log(tag))
      .then(() => NfcManager.requestTechnology(NfcTech.MifareClassic))
      .then(() => NfcManager.getTag())
      .then(tag => {
        this.setState({ tag });
        return NfcManager.mifareClassicGetSectorCount();  ///<-------- stopped
      })
      .then(sectorCount => {
        this.setState({ sectorCount });
      })
      .then(() => {
        let sector = parseInt(this.state.sector);
        if (isNaN(sector)) {
          this.setState({ sector: '0' });
          sector = 0;
        }
```
this is the result i get: 
`{"techTypes":["android.nfc.tech.NfcA","android.nfc.tech.MifareClassic","android.nfc.tech.NdefFormatable"],"id":"NNNNNN"}`

**Comment by cgbsolutions** [comment]
It looks like this issue is still preset in the example code, any chance of an updated example with this resolved?
