### ISSUE TITLE
Expo 45 and NFC-Manager throws "Not support in this device"

### ISSUE THREAD

**Issue by sajadghawami** [revtel/react-native-nfc-manager#574]
Hey,

after updating Expo and this package i am getting a "Not support in this device" error. 
Everything was working fine before with `"expo": "^43.0.0"` and "react-native-nfc-manager": "^3.3.0".

# Setup

`package.json`
```    
"expo": "^45.0.0",
"react-native-nfc-manager": "^3.14.0",
```

`app.json`
```
"plugins": ["react-native-nfc-manager"],
```

And now i just do this in a hook:

```js
import NfcManager from 'react-native-nfc-manager';
NfcManager.start();

const  useNFC = () => {
...
}
```

And it will throw:

```
Error: Not support in this device
```

# Device Details

```
iPhone X
iOS 15.6.1

Building the App on a M1
```

Any help would be much appreciated.

**Comment by whitedogg13** [comment]
@sajadghawami in `3.14.0`, some native code has been updated for `iOS`, you will need to update these part for your project. 

For `non-expo` project, we normally redo `pod install` to update the xcode project, in your case you should do whatever equavalent for `expo`.

**Comment by sajadghawami** [comment]
@whitedogg13 

thanks for the quick reply.

I actually had the same issue before upgrading to the latest version of this package... i had `"react-native-nfc-manager": "^3.3.0",` before and it was throwing the same error when i did the expo upgrade.

Also, i am having the same issue with Android.
