### ISSUE TITLE
Oops! NFCError:2

### ISSUE THREAD

**Issue by phucph1998** [revtel/react-native-nfc-manager#580]
LOG  Oops! NFCError:2

   "react": "18.1.0",
    "react-native": "0.70.4",
    "react-native-nfc-manager": "3.0.3"

Both ios and android error. i using tech NfcTech.IsoDep

**Comment by GeorgeTsendra66** [comment]
@phucph1998 Hi, I have met same problem. 
Have you fixed? any solutions?

**Comment by khasbilegt** [comment]
Hey there, look at the log window of xcode. I had the same issue and I fixed it by setting the correct AID in the Info.plist.
