### ISSUE TITLE
Recognized by Shortcuts but not App

### ISSUE THREAD

**Issue by hkaras19** [revtel/react-native-nfc-manager#582]
I copied the example reader from the starter code and followed all of the setup instructions for iOS; however, I am not able to identify my tag. The UI does pop up, but nothing happens. Interestingly, I am able to identify the card using the Shortcuts app on my iPhone. Is this particular card not supported by the library?

Link to Tag: https://www.adafruit.com/product/359

**Comment by whitedogg13** [comment]
Hi, @hkaras19 what you mentioned is possible. Some NFC tags can only be discovered by Apple's internal app like shortcut. No public API available for discovering these tags.

You can do following steps to check if this is the case:
- use [react-native-nfc-rewriter](https://apps.apple.com/tw/app/nfc-rewriter/id1551243964) to read the tag. This app is written in RN and uses this library, open sourced [here](https://github.com/revtel/react-native-nfc-rewriter) 
- use 3rd party app such as [NXP Tag Info](https://apps.apple.com/tw/app/nfc-taginfo-by-nxp/id1246143596) to read the tag
 
If the second one can discover the tag but our app cannot, please feel free to re-open this issue.
