### ISSUE TITLE
Trying to mock nfcManager using react native testing library, but it doesn't work & nfcManager.start()

### ISSUE THREAD

**Issue by PanosPapad** [revtel/react-native-nfc-manager#597]
Hello,

I am developing an android app that requires to read nfc tags, so I am using this library. However, I have come across two issues that I could not figure out at all. 

- What does the `nfcManager.start()` function do? I realized that the app was working even if I remove it from the top of the method. 
- I want to test the page, so I try to mock `nfcManager`. However, I always get this issue ` TypeError: _reactNativeNfcManager.default.start is not a function` or `TypeError: _reactNativeNfcManager.default.isSupported is not a function` etc with all the functions of the interface. What I try to do is 

`const mockNfcManager = jest.fn();`

`jest.mock("react-native-nfc-manager", ()=>({ 
  NfcManagerModule: {
    start: mockNfcManager,
  },
}));`   

and then render the component and check if `expect(mockedNavigate).toHaveBeenCalled()`

Sorry for the long message, but I saw you are pretty responsive in the issues of this library, and also I have not seen anyone mentioning these issues anywhere, so I was hoping to solve this issue here :) Thanks a lot!

**Comment by whitedogg13** [comment]
Hi @PanosPapad , sorry for the late response.

The `start()` function is simply used to initialize the native layer.

Regarding the `mock`, I think @dylanclements 's suggestion should work:

```javascript
jest.mock('react-native-nfc-manager', () => ({
  start: () => Promise.resolve(),
  isSupported: () => Promise.resolve(false), // bypass NFC feature when running test cases
}));
```
