### ISSUE TITLE
Read Android HCE from iPhone

### ISSUE THREAD

**Issue by duychuongvn** [revtel/react-native-nfc-manager#603]
Hello forks,
I'm writing application which that has following components and  specification:
- Components: 
     + NFC Card with ISO14443 standard
     + Android: works as an NFC card reader and  a HCE application that simulates NFC Card with ISO14443 standard
     + iOS: works as NFC Card reader 
- Specification:
   There are two applications: A works as NFC Card reader on both Android and IOS, B works as NFC Card on Android
    - Case 1: Tap application A that runs on Android to NFC card ==> IT WORKS
    - Case 2: Tap application A that runs on Android to B (Android HCE) ==> IT WORKS
    - Case 3: Tap application A that runs on iOS to NFC card ==> IT WORKS
    - Case 4: Tap application A that runs on iOS to  B (Android HCE) ==> IT DOES NOT WORK

To allow application A run on iOS can read NFC Card, I define value TAG for com.apple.developer.nfc.readersession.formats and AID for com.apple.developer.nfc.readersession.iso7816.select-identifiers

I also use IsoDep handle to request NFC Technology: NfcManager.requestTechnology([NfcTech.IsoDep])

The error message is: "Missing required entitlement", as I understand is the NFC Connection is not made between iOS and Android

Please help me to know is it possible to communicate between Android and iOS via NFC based on ISO14443 standard?
If yes, please guide me how to do it with react-native-nfc-manaager library?

Thank you very much.

**Comment by tgreco** [comment]
How did you get this to work?
I get `HCE_STATE_READ` firing off then `HCE_STATE_DISCONNECTED`.
But never see the `WRITE_FULL` or `WRITE_PARTIAL` fire.
