### ISSUE TITLE
NFC Manager sometimes deletes ndef from tag's available technologies

### ISSUE THREAD

**Issue by MErenTalan** [revtel/react-native-nfc-manager#614]
Hi I'm writing an app for ndef read/write with react-native-nfc-manager. It successfully works most of the time but sometimes it deletes ndef from "available technologies". I can't write to nfc until clone from another ndef tag with ST25 app.

I couldn't find a way to add cloning on my app with react-native-nfc-manager. One time I achieved to fix the nfc with using direct bytes with writeNdefMessage but didn't work again.

How can I handle this situation on my app? My NFC Write code:

```
                try {
              await NfcManager.requestTechnology(NfcTech.Ndef)
              await NfcManager.ndefHandler.writeNdefMessage([
               0xD1,0x01,0x0B,0x55,0x04,0x67,0x6F,0x6F,0x67,0x6C,0x65,0x2E,0x63,0x6F,0x6D
              ]);

            } catch (error) {
              console.log(error);
            } finally {
              NfcManager.cancelTechnologyRequest().catch(() => 0);
            }

```

**Comment by Ludeco27** [comment]
Hello my friend, how do I get in touch with you, I want to make an nfc apk, can you help me to get the values ​​right
