### ISSUE TITLE
dependency issue with @expo/config-plugins, for expo SDK48.

### ISSUE THREAD

**Issue by equalogix** [revtel/react-native-nfc-manager#619]
I tried to upgrade from expo SDK46 to 48 but it is failing because the of a dependency with @expo/config-plugins, for SDK48 requires `^6.0.0` and version 3.14.2 of react-native-nfc-manager requires `^4.0.16`
```
"dependencies": {
    "@expo/config-plugins": "^4.0.16"
  },
```
Any idea on how to resolve this?

**Comment by cavasinf** [comment]
Same case here for the SDK47, 
it requires "@expo/config-plugins": `~5.0` but locked with `^4.0.16`

**Comment by dylanclements** [comment]
[Have updated @expo/config-plugins](https://github.com/revtel/react-native-nfc-manager/pull/631)

See if issue is resolved now

**Comment by lawnguyen** [comment]
@dylanclements's update to `@expo/config-plugins@^6.0.1` doesn't address SDK47 which still depends on  "@expo/config-plugins": ~5.0

**Comment by dylanclements** [comment]
@hezzze [on it](https://github.com/revtel/react-native-nfc-manager/pull/649)
