### ISSUE TITLE
Using makeReadOnly crashes the app and makes NFC disabled until phone restart

### ISSUE THREAD

**Issue by daaain** [revtel/react-native-nfc-manager#620]
When using `makeReadOnly` the app crashes (there's a `java.io.IOException` in Sentry that might be due to this) to the point that the UI is completely frozen, the JS error handler doesn't get called and the NFC functionality is completely disabled on the entire Android OS level (other apps can't read NFC any more) until a hard reboot.

So it's almost surely something not quite in the native layer and after most of the day spent debugging I thought I'd try in the reference app and it's the same! Attaching screenshots of the tag below, but it's an NDef one with a custom media type that otherwise has been working for us for years.

Do you know what it could be or how could I diagnose it? I'm using Android 12/13 and version `3.14.1` – by the looks of it the latest is just a small iOS fix.

![image](https://user-images.githubusercontent.com/69962/227612536-97122793-98f4-4cd9-86af-56778398610b.png)
![image](https://user-images.githubusercontent.com/69962/227612555-c784c115-8724-4024-ac16-b818086e9da8.png)

**Comment by MattEndstate** [comment]
Running into the same issue here on a Pixel 6a running Android 13 and version `3.14.1`.
I have an older Pixel 5a running Android 11 that is not affected by this issue.

**Comment by daaain** [comment]
Please remove stale label, it would be great if this error was handled more gracefully in the library so there's no crash.

**Comment by Mehly** [comment]
I'm facing the very same issue.  NFC becomes device-globally unusable until device-restart.

**Comment by aminhdev** [comment]
I got the same problem
