### ISSUE TITLE
EMV Credit/Debit Card Read

### ISSUE THREAD

**Issue by cwtaras** [revtel/react-native-nfc-manager#632]
Hello,
I want to add NFC payment to my app but I couldn't find a solution. My app is targeting the merchants and I want to make it possible for them get payments from their clients through my app. Is it possible to do it with this package, if so, how can i implement it? Thanks in advance.

**Comment by diklou** [comment]
I'm also interested about this

**Comment by Noitidart** [comment]
Anyone able to figure out how to do this? Android and/or iOS? Stripe makes it sound like iOS can now do this as well - https://stripe.com/en-au/terminal/tap-to-pay

<img width="462" alt="image" src="https://github.com/revtel/react-native-nfc-manager/assets/6372489/d39bc154-0a05-473d-9ef2-58c968923990">
