### ISSUE TITLE
fail to get current activity

### ISSUE THREAD

**Issue by daheeahn** [revtel/react-native-nfc-manager#640]
When I use `NfcManager.getLaunchTagEvent()` , 
```
      try {
        const tag = await NfcManager.getLaunchTagEvent();
      } catch (error) {
        console.log(error)
      }
```

I get an error below.  
```
fail to get current activity
```
![image](https://github.com/revtel/react-native-nfc-manager/assets/38369729/e0daeb93-21ae-416e-a1dc-3225ff33b64c)
I think you caught an error because currentActivity is null. What should I do in this case?
Why is this happening?

`react-native-nfc-manager` version is `3.14.5`

**Comment by AftabUfaq** [comment]
still has same issue
