### ISSUE TITLE
getBackgroundTag not being fired

### ISSUE THREAD

**Issue by sajadghawami** [revtel/react-native-nfc-manager#656]
Hey there,

i wrote the following hook:

```tsx
import React from "react";
import NfcManager, { NfcEvents } from "react-native-nfc-manager";

NfcManager.start();

const useNFCTest = () => {
  const onBackgroundTag = async (tag: any) => {
    console.log("onBackgroundTag", tag);
  };

  React.useEffect(() => {
    const initalizeBackgroundTag = async () => {
      const bgTag = await NfcManager.getBackgroundTag();
      onBackgroundTag(bgTag);

      // listen to other background tags after the app launched
      NfcManager.setEventListener(
        NfcEvents.DiscoverBackgroundTag,
        onBackgroundTag
      );
    };
    initalizeBackgroundTag();
  }, []);
};

export default useNFCTest;

```

### Here is what happens:

- `onBackgroundTag null` on startup (which is fine, since i didn't try with a tag)
- i hold a tag to the nfc-reader, i will get the native overlay that the tag has been read
- in the app nothing happens, not logging
- when i click on the overlay, also nothing happens, no logging

### Environment:

- iOS device
- `react-native-nfc-manager@3.14.6`
- Universal Links implemented and fully working 

I also checked [react-native-nfc-rewriter](https://github.com/revtel/react-native-nfc-rewriter) how it is implemented ([here](https://github.com/revtel/react-native-nfc-rewriter/blob/551b0872cc2dcad6c40c921f3475236288e2c509/src/Screens/Home/index.js)) but could not find a proper difference.

### My questions
- What am i doing wrong?
- And then, Is the tag supposed to be read without the need to click on the overlay?

Thank you.

**Comment by phuocnh01** [comment]
Hi! I faced the same issue and after move ```NfcManager.start()``` into ```initalizeBackgroundTag()``` everything work as expected.
Hope this will work to you

**Comment by phuocnh01** [comment]
sorry! I forgot  i also downgraded to ```"react-native-nfc-manager": "3.13.5"```
Here are my source:
```typescript
const [isEnable, setIsEnable] = useState(false);
 const [message, setMessage] = useState<any>();

async function initNfc() {
    try {
      const supported = await NfcManager.isSupported();
      if (supported) {
        await NfcManager.start();
      }

      const getEnable = await NfcManager.isEnabled()
      setIsEnable(getEnable)

      const bgTag: TagEvent | null = await NfcManager.getBackgroundTag()
      if (bgTag) {
        const msg = Ndef.text.decodePayload(new Uint8Array(bgTag.ndefMessage[1].payload))
        setMessage(msg)
      }
    } catch (error) { }
  }

  useEffect(() => {
    initNfc()
  }, [])

**Comment by sajadghawami** [comment]
@phuocnh01 

Thank you for clarifying!

Are you using the `eventListener` somewhere:

```tsx
      NfcManager.setEventListener(
        NfcEvents.DiscoverBackgroundTag,
        onBackgroundTag
      );
```

Because reading the nfc and then opening the app does work, but the background listener seems not to work... So iOS is actually showing the toast/popup that a nfc chip has been read, but in my application it will not be logged

**Comment by sajadghawami** [comment]
hey @whitedogg13,

sorry for tagging you directly, but i am not able to fix this... not sure if this is a bug or my implementation.

thank you!

**Comment by wordisthebird** [comment]
@sajadghawami did you make any progress with this?

**Comment by wordisthebird** [comment]
> @wordisthebird
> 
> unfortunately not

no worries :) let me know if you do!
