### ISSUE TITLE
NfcManager.java Build Error with setNdefPushMessage

### ISSUE THREAD

**Issue by adeelcheeema** [revtel/react-native-nfc-manager#657]
NfcManager.java -> setNdefPushMessage ->  nfcAdapter.setNdefPushMessage(msgToPush, currentActivity);

**Issue Description:**

When trying to build the Android project, I encountered an issue related to **NfcManager.java** and the **setNdefPushMessage** function. Specifically, the build fails if I comment out the line **nfcAdapter.setNdefPushMessage(msgToPush, currentActivity)**;. However, the build succeeds when this line is included.

Expected Behavior:
The build should complete successfully even when the line nfcAdapter.setNdefPushMessage(msgToPush, currentActivity); is commented out.

Actual Behavior:
The build fails when the line nfcAdapter.setNdefPushMessage(msgToPush, currentActivity); is commented out.

`NfcAdapter nfcAdapter = NfcAdapter.getDefaultAdapter(context);
nfcAdapter.setNdefPushMessage(msgToPush, currentActivity);
callback.invoke();`

<img width="1103" alt="Screenshot 2023-08-15 at 10 20 26 AM" src="https://github.com/revtel/react-native-nfc-manager/assets/36962178/1bb65090-bc27-48cb-bbfa-b35315b08ca6">

This function has been removed in the Nfc Adapter Documentation. You can find more information about this change at the following link:

[Changes in android.nfc.NfcAdapter](https://developer.android.com/sdk/api_diff/34/changes/android.nfc.NfcAdapter)

<img width="480" alt="Screenshot 2023-08-15 at 11 15 33 AM" src="https://github.com/revtel/react-native-nfc-manager/assets/36962178/ff32d5d4-5a68-4509-b735-2759c5c302cd">

**Comment by kirandchavan** [comment]
yes, this error is coming with react native version 
`"react-native": "0.72.4",`
`"react-native-nfc-manager": "^3.14.6",`

**Comment by whitedogg13** [comment]
Hi @nicolasburtey @adeelcheeema @kirandchavan you're right! I have removed the deprecated api and released `v3.14.7`, please give it a try & thanks for the information!
