### ISSUE TITLE
'new NativeEventEmitter()' requires a non-null argument.

### ISSUE THREAD

**Issue by itsemirhanengin** [revtel/react-native-nfc-manager#676]
When I try to run NFC manager, I get 'new NativeEventEmitter()' requires a non-null argument. issue. I configured the XCode as the what documentation says, but I get this error.

**Comment by Jose-Manuel18** [comment]
The only way i solved this is running on the ios folder: 
-pod deintegrate
-pod install
-rebuild the project on xcode

**Comment by Dimasprog** [comment]
@itsemirhanengin, did u find any solution?
