### ISSUE TITLE
ISO 14443-4 not reading in IOS

### ISSUE THREAD

**Issue by Tboules** [revtel/react-native-nfc-manager#677]
Hey y'all,

just got a batch of NFC chips from a manufacturer that are ISO 14443-4 and they are not registering in IOS. I am able to read them on Android with the app I built but not IOS. 

Here is an image of the tag details

![Screenshot 2023-11-01 at 5 47 51 PM](https://github.com/revtel/react-native-nfc-manager/assets/68886354/55284594-ce46-40d8-aad9-fc2839335520)

type ISO 14443 - 3A seem to work fine
Any ideas?

**Comment by Danushka96** [comment]
Same here, tried exact card type from android and it's working, but in ios its not detecting

**Comment by miklund** [comment]
Same issue here. Did you find out a solution or a workaround?


```
await NfcManager.requestTechnology(NfcTech.Ndef);
const tag = await NfcManager.getTag();
console.log('Tag metadata:', tag);
const data = await NfcManager.ndefHandler.getNdefMessage();
```

`getTag()` returns an empty object, and `getNefMessage()` throws an error with message "No ndef available".

I've also tried requestTechnology `IsoDep` and `transceive` but this fails with `Not connected`.
