### ISSUE TITLE
Build Failed after install react-native-nfc-manager - json.put("canMakeReadOnly", JSONObject.NULL)

### ISSUE THREAD

**Issue by EmanuelDesarrollo** [revtel/react-native-nfc-manager#680]
Performing the installation for a demo on Android after installing and trying to compile, the error shown in the image appeared: 

![image](https://github.com/revtel/react-native-nfc-manager/assets/44582686/34eb5dd4-7cc9-4fa6-bae3-6f51d00a230a)

`\node_modules\react-native-nfc-manager\android\src\main\java\community\revteltech\nfc\Util.java:47: error: ';' expected json.put("canMakeReadOnly", JSONObject.NULL)`

After going to the path shown in the error it is evident that a semicolon is indeed missing on the indicated line. After correcting this, it allows compiling without problems.

Versions:
`"react-native": "0.72.7", 
"react-native-nfc-manager": "^3.14.10"`

**Comment by whitedogg13** [comment]
@EmanuelDesarrollo It's such a stupid error... I just fixed it and published `v3.14.11`. Thanks for reporting that!
