### ISSUE TITLE
How can I format an NFCTag of typeV from NDEF.formatable to NDEF in iOS?

### ISSUE THREAD

**Issue by Meenorpb** [revtel/react-native-nfc-manager#698]
Hello @whitedogg13 
I have NFC tag with TypeV, but it is ndefformatable, so I am unable to write NDEF message from the iOS platform. Can anyone provide a quick fix or example? 
Note: I need to format the NFC tag from my own app, not from a third-party app.

**Comment by richi902** [comment]
i would need to do the same.
