### ISSUE TITLE
how to read data returned from transceive ?

### ISSUE THREAD

**Issue by nickticket2u** [revtel/react-native-nfc-manager#705]
This is not really an issue, so I wish to apologise in advance. I've been trying to seek answer in reddit/stackoverflow/fb without anyone answering.

(ntag213) I use the read command 0x30 and followed by page address (eg 0x60)

on IOS (sendMifareCommandIOS), it returns 16 byte array when I display the response

but on android (transceive) , it displays "[Function Anonymous]"

does anyone know how do I actually read the data on android ? 

any help is greatly appreciated

**Comment by pke** [comment]
`sendMifareCommandIOS` as the name suggests is not available on Android and it should actually crash, when you try to invoke it.
You have to use `transceive` on Android I am afraid.
