### ISSUE TITLE
ISO15693 customCommands & password protection not working

### ISSUE THREAD

**Issue by outboundexplorer** [revtel/react-native-nfc-manager#710]
I have been trying to set password protection for the ICODE SLIX.

The data set here at [dataset](https://www.nxp.com/docs/en/data-sheet/SL2S2002_SL2S2102.pdf).

I am using the NfcManager.iso15693HandlerIOS.customCommand() as I am currently developing on IOS.

The react-native-nfc-manager has been fantastic to work with type 2 tags.  But really running into problems on setting password protection for the type 5 tags.

As i understand it, I need to follow the following steps to add password protection to ISO15693 tags.

1. Generate random number
2. Set password
3. Write password
4. Lock password
5. Enable password protection

Here is an example of a command that I am using just to generate a random number.

```javascript
try {
    const tag = await NfcManager.getTag();
    const icMfgCode = 0x04; // Assuming NXP's manufacturer code
    const uidBytes = tag?.id.match(/.{1,2}/g).map(byte => parseInt(byte, 16));
    const response = await NfcManager.iso15693HandlerIOS.customCommand({
      flags: 0x02,
      commandCode: 0xb2,
      data: [icMfgCode, ...uidBytes],
    });

    console.log('response for random number:', response);
  } catch (error) {
    console.error('Failed to get random password:', error);
  } finally {
    NfcManager.cancelTechnologyRequest().catch(err => console.error(err));
  }
```

![Screenshot 2024-04-07 at 16 40 18](https://github.com/revtel/react-native-nfc-manager/assets/6761832/524955c6-9224-4858-b749-d4bafcebb532)

This is the structure for the command as defined by the product data sheet.

**Comment by psusundrem** [comment]
<img width="707" alt="ST_ISO15693NFCChip" src="https://github.com/revtel/react-native-nfc-manager/assets/30401556/288eeaf3-229f-4e2b-8d12-890c21cd02d8">

Avoid using the 64-bit optional UID in the command with the 0x02 flag. If you still want to use a UID, try using the flags: 0x22 and data: [icMfgCode, ...uidBytes.reverse()]. The UID bytes are fetched in reverse order.

Here’s how I use a custom command for the "present password" command for an ST type 5 chip:
const checkPasswordIosCmd = {
  flags: Nfc15693RequestFlagIOS.HighDataRate, //Bit 2 SET, High data rate
  customCommandCode: 0xb3, //Present Password Command code
  customRequestParameters: [0x01, 0x55, 0xAA, 0x55, 0xAA, 0xD7, 0xD3, 0x03, 0xE7],
};
const resp = await NfcManager.iso15693HandlerIOS.customCommand(checkPasswordIosCmd);

In this command, the customRequestParameters array starts with the RF password number, followed by the 8-byte actual password.

**Comment by outboundexplorer** [comment]
I will give this a try.  Thanks.

**Comment by flyskywhy** [comment]
> <img alt="ST_ISO15693NFCChip" width="707" src="https://private-user-images.githubusercontent.com/30401556/335029082-288eeaf3-229f-4e2b-8d12-890c21cd02d8.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzUwOTE5MzcsIm5iZiI6MTc3NTA5MTYzNywicGF0aCI6Ii8zMDQwMTU1Ni8zMzUwMjkwODItMjg4ZWVhZjMtMjI5Zi00ZTJiLThkMTItODkwYzIxY2QwMmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDAyVDAxMDAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZWY1MWNlNGE5MzExMmU5NzYzZjQ3NzE3YWViOTA5MGM3NzA4NTJjY2NmNTE0MmIxYzE4YjM1MWU3YTlkODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VrNFART20dssp4PHYt_stRA8w_n5cIwgwpHm-cB4gcU">
> Avoid using the 64-bit optional UID in the command with the 0x02 flag. If you still want to use a UID, try using the flags: 0x22 and data: [icMfgCode, ...uidBytes.reverse()]. The UID bytes are fetched in reverse order.
> 
> Here’s how I use a custom command for the "present password" command for an ST type 5 chip: const checkPasswordIosCmd = { flags: Nfc15693RequestFlagIOS.HighDataRate, //Bit 2 SET, High data rate customCommandCode: 0xb3, //Present Password Command code customRequestParameters: [0x01, 0x55, 0xAA, 0x55, 0xAA, 0xD7, 0xD3, 0x03, 0xE7], }; const resp = await NfcManager.iso15693HandlerIOS.customCommand(checkPasswordIosCmd);
> 
> In this command, the customRequestParameters array starts with the RF password number, followed by the 8-byte actual password.

iOS not support addressed flag in custom command, so 0x02 can but 0x22 can not work, ref to `readRegNfcVTag()` in https://github.com/flyskywhy/react-native-nfc-rw/blob/main/index.js
