### ISSUE TITLE
Can't retrieve tag information with background tag on IOS

### ISSUE THREAD

**Issue by ImperialCrowns** [revtel/react-native-nfc-manager#715]
Hey !

I wrote the following code :

```typescript
const initNFC = () => {
  const onBackgroundTag = async (tag: TagEvent | null) => {
    console.log('onBackgroundTag', tag);
  };

  const initalizeBackgroundTag = async () => {
    // changed
    await NfcManager.start();

    const bgTag = await NfcManager.getBackgroundTag();
    onBackgroundTag(bgTag);

    // listen to other background tags after the app launched
    NfcManager.setEventListener(NfcEvents.DiscoverBackgroundTag, onBackgroundTag);
  };
  initalizeBackgroundTag();
};

function App() {
  initNFC();
  return (
    <View>
      <Text>Hello World</Text>
    </View>
  );
}

export default App;
```

I'm trying to retrieve tag informations when reading tag in background but the return value of NfcManager.getBackgroundTag is always null.
What am I doing wrong ? Is there something I miss ? Is it possible to do it ?

### Environment:
- Device: Iphone 14 Pro Max
- iOS: 17.4.1
- react-native-nfc-manager@3.14.14
- Universal Links implemented and fully working

I've already tried many solutions proposed in previous issues, and it don't work.

**Comment by BhavyaCodeAlchemy** [comment]
It's Working fine in android ?

**Comment by ImperialCrowns** [comment]
Yes, on Android it works perfectly.

**Comment by gigeos** [comment]
Same for me

I can't retrieve the tagId when the application is launched in background on iOS thanks to the little NFC notification that appears when a tag is touched.

**Comment by wuguishifu** [comment]
I'm also having this issue, I can't get any scan information.

Also, if the issue is tagged for iOS, saying that it works perfectly on Android is probably not going to be relevant information.

**Comment by ChronoByteCosmonaut** [comment]
Same!!!
