### ISSUE TITLE
How to read Citizen ID Card?

### ISSUE THREAD

**Issue by Nam-Anh-99** [revtel/react-native-nfc-manager#727]
How to read Citizen ID Card? :((

**Comment by caijiami** [comment]
你好大佬 解决了吗，这个插件可以识别身份证吗

**Comment by sa1utep1z** [comment]
> 你好大佬 解决了吗，这个插件可以识别身份证吗

可以识别身份证吗

**Comment by birkanozdamar** [comment]
've been trying APDU commands for days. Has anyone been able to solve this?

**Comment by Abramovick** [comment]
> I've been trying APDU commands for days. Has anyone been able to solve this?

Hi @ozbirkan did you manage to figure this out?
