### ISSUE TITLE
Android Indicator

### ISSUE THREAD

**Issue by jigar-parmar-13** [revtel/react-native-nfc-manager#741]
In Android side while reading nfc tag does any kind of pop up modal will be display like ios or not ? and also please let me know which android version will support this? bcoz i get error in android 11 with checking await NfcManager.isSupported();

**Comment by pke** [comment]
No, for Android you have to create a UI yourself.

**Comment by jigar-parmar-13** [comment]
Okay Thanks for reply @pke, which android version will support this? bcoz i get error in android 11 with checking await NfcManager.isSupported();
